spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/security
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true