spring:
  liquibase:
    change-log: db/changelog/changelog-master.yaml
    enabled: true
  datasource:
#    url: jdbc:postgresql://postgres:5434/telegram_bot
    username: user
    password: password
    url: jdbc:postgresql://localhost:5435/telegram_bot
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092


