services:
  postgres:
    image: postgres:16.3-alpine3.20
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  task5:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres

volumes:
  postgres_data: